# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-16 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Market', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxfOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_price', models.FloatField()),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.AxfUser')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.CreateModel(
            name='AxfOrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('og_num', models.IntegerField()),
                ('og_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.AxfGoods')),
                ('og_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.AxfOrder')),
            ],
            options={
                'db_table': 'axf_ordergoods',
            },
        ),
    ]
